name: CI in branch develop

on:
  push:
    paths-ignore:
    - '.github/**'
    branches: [ develop ]
  pull_request:
    paths-ignore:
    - '.github/**'
    branches: [ develop ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests with Maven
        run: mvn -B clean compile --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
